# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: "Create docker files"
  inputs:
    filePath: 'scripts/create_docker_files.sh'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      ASPNETCORE_ENVIRONMENT=Production
      SQL_DB_SBANKEN=$(sqlDbSbanken)
      SBANKEN_API_PORT=8081
    projectName: "hub-sbanken"
    action: 'Build services'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Pay-As-You-Go(1fc9558a-bc74-46df-9a2e-d54c65f169b0)'
    azureContainerRegistry: '{"loginServer":"rhesystemscontainerregistry.azurecr.io", "id" : "/subscriptions/1fc9558a-bc74-46df-9a2e-d54c65f169b0/resourceGroups/rhe-systems-rg/providers/Microsoft.ContainerRegistry/registries/rhesystemscontainerregistry"}'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      ASPNETCORE_ENVIRONMENT=Production
      SQL_DB_SBANKEN=$(sqlDbSbanken)
      SBANKEN_API_PORT=8081
    projectName: 'hub-sbanken'
    action: 'Push services'