# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'macOS-10.14'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: "Create docker files"
  inputs:
    filePath: 'scripts/create_docker_files.sh'

- task: DockerInstaller@0
  displayName: "Install docker"
  inputs:
    dockerVersion: '19.03.13'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'