# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: "Create docker files"
  inputs:
    filePath: 'scripts/create_docker_files.sh'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      ASPNETCORE_ENVIRONMENT=Production
      SQL_DB_SBANKEN=$(sqlDbSbanken)
      SBANKEN_API_PORT=8081
    projectName: "hub-sbanken"
    action: 'Build services'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: $(azureContainerRegistry) 
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      ASPNETCORE_ENVIRONMENT=Production
      SQL_DB_SBANKEN=$(sqlDbSbanken)
      SBANKEN_API_PORT=8081
    projectName: "hub-sbanken"
    action: 'Push services'