version: '3.7'

networks:
    hub-network:
        name: hub-network
    hub-db-network:
        name: hub-db-network
        
            
services:
    sbanken-workers:
        container_name: "sbanken_worker"
        build:
            context: ./
            dockerfile: Sbanken.BackgroundWorker/Dockerfile
        image: "rhe89/hub-sbanken-worker"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - SQL_DB_SBANKEN=${SQL_DB_SBANKEN}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network

    sbanken-api:
        container_name: "sbanken_api"
        build: 
            context: ./
            dockerfile: Sbanken.Web.Api/Dockerfile
        image: "rhe89/hub-sbanken-api"
        hostname: "sbanken-api"
        ports:
            - "${SBANKEN_API_PORT}:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=http://+
            - SQL_DB_SBANKEN=${SQL_DB_SBANKEN}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network