version: '3.7'

services:
    banking-service-bus-queue-host:
        container_name: "banking_service_bus_queue_host"
        build:
            context: ./
            dockerfile: Banking.HostedServices.ServiceBusQueueHost/Dockerfile
        image: "rhe89/hub-banking-service-bus-queue-host"

    banking-scheduled-host:
        container_name: "banking_scheduled_host"
        build:
            context: ./
            dockerfile: Banking.HostedServices.ScheduledHost/Dockerfile
        image: "rhe89/hub-banking-scheduled-host"

    banking-api:
        container_name: "banking_api"
        build:
            context: ./
            dockerfile: Banking.Web.Api/Dockerfile
        image: "rhe89/hub-banking-api"

    banking-app:
        container_name: "banking_app"
        build:
            context: ./
            dockerfile: Banking.Web.WebApp/Dockerfile
        image: "rhe89/hub-banking-app"