version: '3.7'

services:
    sbanken-service-bus-queue-host:
        container_name: "sbanken_service_bus_queue_host"
        build:
            context: ./
            dockerfile: Sbanken.HostedServices.ServiceBusQueueHost/Dockerfile
        image: "rhe89/hub-sbanken-service-bus-queue-host"

    sbanken-scheduled-host:
        container_name: "sbanken_scheduled_host"
        build:
            context: ./
            dockerfile: Sbanken.HostedServices.ScheduledHost/Dockerfile
        image: "rhe89/hub-sbanken-scheduled-host"

    sbanken-api:
        container_name: "sbanken_api"
        build: 
            context: ./
            dockerfile: Sbanken.Web.Api/Dockerfile
        image: "rhe89/hub-sbanken-api"

    sbanken-app:
        container_name: "sbanken_app"
        build: 
            context: ./
            dockerfile: Sbanken.Web.WebApp/Dockerfile
        image: "rhe89/hub-sbanken-app"