version: '3.7'

services:
    sbanken-workers:
        container_name: "sbanken_worker"
        build:
            context: ./
            dockerfile: Sbanken.BackgroundWorker/Dockerfile
        image: "rhe89/hub-sbanken-worker"

    sbanken-api:
        container_name: "sbanken_api"
        build: 
            context: ./
            dockerfile: Sbanken.Web.Api/Dockerfile
        image: "rhe89/hub-sbanken-api"